name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: Run Checks (Lint & Typecheck)
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  deploy:
    name: Deploy to Fly.io
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency: deploy-group # Гарантує, що одночасно виконується лише один деплой

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
